id: P3040610B
initial_creation_type: ocr
source_metadata:
  volumes:
    e939345a4b584491aefb13b87afedd3c:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སངས་རྒྱས་རྗེས་སུ་དྲན་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
